### ISSUE TITLE
Standardize contract function return types to Result/Error

### ISSUE THREAD

**Issue by coostendorp** [pixelaw/core#10]
To be researched a bit, but ideally Result is a felt252, and webapp consistently deals with this (Show a Toast?)
Errors likewise.

To be implemented on the example contracts and the webapp.

But if length is 0, webapp should not show anyting

**Comment by mariz-ov** [comment]
So the issue behind this was the webapp wasn't showing errors from asserts, but I just realized that the webApp can indeed get these errors. So I was thinking, what if developers use assert to show error and then use alerts if they want to show a successful transaction. I think this would simplify things

**Comment by mariz-ov** [comment]
Deciding to use asserts and send alerts instead of enforcing developers to return a result
